import { SportEvent, SportCategory, TravelDemand, TicketDemand } from '@/types/events';

export const f1Events: SportEvent[] = [
    {
        id: 'f1-australia-2026',
        name: 'Australian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'March 6–8, 2026',
        startDate: new Date('2026-03-06'),
        endDate: new Date('2026-03-08'),
        country: 'Australia',
        venue: 'Albert Park Circuit',
        city: 'Melbourne',
        description: 'Season opener in Melbourne with record-breaking attendance and massive international travel.',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Season Opener', 'Street Circuit', 'VIP Available'],
        highlights: ['Record-breaking attendance', 'Huge international travel', 'Festival atmosphere'],
        targetAudience: ['International Fans', 'F1 Enthusiasts', 'Luxury Travelers']
    },
    {
        id: 'f1-china-2026',
        name: 'Chinese Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'March 13–15, 2026',
        startDate: new Date('2026-03-13'),
        endDate: new Date('2026-03-15'),
        country: 'China',
        venue: 'Shanghai International Circuit',
        city: 'Shanghai',
        description: 'Sprint weekend in Shanghai featuring the exciting sprint race format.',
        imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Sprint Weekend', 'Asia', 'Night Sessions'],
        highlights: ['Sprint race format', 'Asian market appeal', 'Modern facilities'],
        targetAudience: ['Asian Markets', 'Sprint Race Fans']
    },
    {
        id: 'f1-japan-2026',
        name: 'Japanese Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'March 27–29, 2026',
        startDate: new Date('2026-03-27'),
        endDate: new Date('2026-03-29'),
        country: 'Japan',
        venue: 'Suzuka Circuit',
        city: 'Suzuka',
        description: 'Iconic figure-8 circuit beloved by drivers and fans, featuring passionate Japanese crowds.',
        imageUrl: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Classic Circuit', 'Fan Favorite', 'Technical Track'],
        highlights: ['Legendary Suzuka circuit', 'Passionate fans', 'Cherry blossom season'],
        targetAudience: ['Racing Purists', 'Asian Markets', 'Culture Enthusiasts']
    },
    {
        id: 'f1-bahrain-2026',
        name: 'Bahrain Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'April 10–12, 2026',
        startDate: new Date('2026-04-10'),
        endDate: new Date('2026-04-12'),
        country: 'Bahrain',
        venue: 'Bahrain International Circuit',
        city: 'Sakhir',
        description: 'Desert night race under the lights with spectacular atmosphere.',
        imageUrl: 'https://images.unsplash.com/photo-1547038577-4da97b7e6c6e?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Night Race', 'Desert', 'Middle East'],
        highlights: ['Night racing spectacle', 'Modern facilities', 'Desert backdrop'],
        targetAudience: ['Middle East Fans', 'Night Race Enthusiasts']
    },
    {
        id: 'f1-saudi-2026',
        name: 'Saudi Arabian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'April 17–19, 2026',
        startDate: new Date('2026-04-17'),
        endDate: new Date('2026-04-19'),
        country: 'Saudi Arabia',
        venue: 'Jeddah Corniche Circuit',
        city: 'Jeddah',
        description: 'Fastest street circuit in F1 with stunning Red Sea backdrop.',
        imageUrl: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Street Circuit', 'Night Race', 'High Speed'],
        highlights: ['Fastest street circuit', 'Red Sea views', 'Night racing'],
        targetAudience: ['Middle East Fans', 'Speed Enthusiasts']
    },
    {
        id: 'f1-miami-2026',
        name: 'Miami Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'May 1–3, 2026',
        startDate: new Date('2026-05-01'),
        endDate: new Date('2026-05-03'),
        country: 'USA',
        venue: 'Miami International Autodrome',
        city: 'Miami',
        description: 'Sprint weekend in glamorous Miami with celebrity attendance and beach vibes.',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Sprint Weekend', 'USA', 'Celebrity Event', 'Beach City'],
        highlights: ['Sprint race format', 'Celebrity hotspot', 'Miami atmosphere'],
        targetAudience: ['High Spenders', 'Celebrity Watchers', 'US Fans']
    },
    {
        id: 'f1-monaco-2026',
        name: 'Monaco Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'June 5–7, 2026',
        startDate: new Date('2026-06-05'),
        endDate: new Date('2026-06-07'),
        country: 'Monaco',
        venue: 'Circuit de Monaco',
        city: 'Monaco',
        description: 'The crown jewel of F1 - prestigious street circuit through Monte Carlo with extreme luxury and exclusivity.',
        imageUrl: 'https://images.unsplash.com/photo-1563784462041-5f97ac9523dd?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Historic', 'Street Circuit', 'Luxury', 'Prestige'],
        highlights: ['Most prestigious F1 race', 'Extreme luxury', 'Limited seating', 'Heavy foreign tourism'],
        targetAudience: ['High Spenders', 'VIPs', 'Luxury Travelers']
    },
    {
        id: 'f1-canada-2026',
        name: 'Canadian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'May 22–24, 2026',
        startDate: new Date('2026-05-22'),
        endDate: new Date('2026-05-24'),
        country: 'Canada',
        venue: 'Circuit Gilles Villeneuve',
        city: 'Montreal',
        description: 'Sprint weekend on the iconic island circuit with passionate Canadian fans.',
        imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Sprint Weekend', 'Island Circuit', 'Fan Favorite'],
        highlights: ['Sprint race format', 'Passionate fans', 'Beautiful Montreal setting'],
        targetAudience: ['North American Fans', 'Sprint Race Fans']
    },
    {
        id: 'f1-spain-barcelona-2026',
        name: 'Spanish Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'June 12–14, 2026',
        startDate: new Date('2026-06-12'),
        endDate: new Date('2026-06-14'),
        country: 'Spain',
        venue: 'Circuit de Barcelona-Catalunya',
        city: 'Barcelona',
        description: 'Technical circuit in beautiful Barcelona, popular testing venue.',
        imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Technical Circuit', 'Europe', 'Testing Venue'],
        highlights: ['Technical challenge', 'Barcelona tourism', 'European fans'],
        targetAudience: ['European Fans', 'Technical Enthusiasts']
    },
    {
        id: 'f1-austria-2026',
        name: 'Austrian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'June 26–28, 2026',
        startDate: new Date('2026-06-26'),
        endDate: new Date('2026-06-28'),
        country: 'Austria',
        venue: 'Red Bull Ring',
        city: 'Spielberg',
        description: 'Scenic mountain circuit with passionate orange army fans and festival atmosphere.',
        imageUrl: 'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Mountain Circuit', 'Festival Atmosphere', 'Scenic'],
        highlights: ['Stunning mountain views', 'Orange army fans', 'Festival vibe'],
        targetAudience: ['European Fans', 'Festival Seekers', 'Nature Lovers']
    },
    {
        id: 'f1-britain-2026',
        name: 'British Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'July 3–5, 2026',
        startDate: new Date('2026-07-03'),
        endDate: new Date('2026-07-05'),
        country: 'Great Britain',
        venue: 'Silverstone Circuit',
        city: 'Silverstone',
        description: 'Sprint weekend at the home of British motorsport - highest ticket sales in modern F1.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Sprint Weekend', 'Historic', 'Home of F1', 'Sold Out'],
        highlights: ['Highest F1 ticket sales', 'Historic Silverstone', 'Sprint format', 'Passionate British fans'],
        targetAudience: ['British Fans', 'F1 History Buffs', 'International Travelers']
    },
    {
        id: 'f1-belgium-2026',
        name: 'Belgian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'July 17–19, 2026',
        startDate: new Date('2026-07-17'),
        endDate: new Date('2026-07-19'),
        country: 'Belgium',
        venue: 'Circuit de Spa-Francorchamps',
        city: 'Spa',
        description: 'The legendary Spa circuit through the Ardennes forest - drivers\' favorite track.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Classic Circuit', 'Drivers Favorite', 'Unpredictable Weather'],
        highlights: ['Legendary Spa circuit', 'Eau Rouge corner', 'Unpredictable weather', 'Driver favorite'],
        targetAudience: ['Racing Purists', 'European Fans', 'Track Enthusiasts']
    },
    {
        id: 'f1-hungary-2026',
        name: 'Hungarian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'July 24–26, 2026',
        startDate: new Date('2026-07-24'),
        endDate: new Date('2026-07-26'),
        country: 'Hungary',
        venue: 'Hungaroring',
        city: 'Budapest',
        description: 'Tight and twisty circuit near beautiful Budapest, known for strategic racing.',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Technical Circuit', 'Strategic Racing', 'Budapest'],
        highlights: ['Strategic racing', 'Budapest tourism', 'Summer race'],
        targetAudience: ['European Fans', 'Strategy Enthusiasts', 'City Tourists']
    },
    {
        id: 'f1-netherlands-2026',
        name: 'Dutch Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'August 21–23, 2026',
        startDate: new Date('2026-08-21'),
        endDate: new Date('2026-08-23'),
        country: 'Netherlands',
        venue: 'Circuit Zandvoort',
        city: 'Zandvoort',
        description: 'Sprint weekend at the banked seaside circuit with massive orange army support.',
        imageUrl: 'https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Sprint Weekend', 'Banked Corners', 'Orange Army', 'Seaside'],
        highlights: ['Sprint format', 'Banked corners', 'Orange army atmosphere', 'Beach location'],
        targetAudience: ['Dutch Fans', 'European Fans', 'Beach Lovers']
    },
    {
        id: 'f1-italy-monza-2026',
        name: 'Italian Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'September 4–6, 2026',
        startDate: new Date('2026-09-04'),
        endDate: new Date('2026-09-06'),
        country: 'Italy',
        venue: 'Autodromo Nazionale Monza',
        city: 'Monza',
        description: 'The Temple of Speed with passionate Tifosi - massive crowd and international fans.',
        imageUrl: 'https://images.unsplash.com/photo-1541872703-74c34d726e5d?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Historic', 'High Speed', 'Tifosi', 'Temple of Speed'],
        highlights: ['Massive Tifosi crowd', 'International fans', 'Fastest circuit', 'Ferrari passion'],
        targetAudience: ['Ferrari Fans', 'Italian Fans', 'Speed Enthusiasts']
    },
    {
        id: 'f1-spain-madrid-2026',
        name: 'Madrid Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'September 11–13, 2026',
        startDate: new Date('2026-09-11'),
        endDate: new Date('2026-09-13'),
        country: 'Spain',
        venue: 'Madrid Street Circuit',
        city: 'Madrid',
        description: 'Brand new street circuit in Spain\'s capital city - debut race.',
        imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['New Circuit', 'Street Circuit', 'Debut Race', 'Capital City'],
        highlights: ['Brand new circuit', 'Madrid debut', 'Street racing', 'Historic city'],
        targetAudience: ['Spanish Fans', 'History Makers', 'City Tourists']
    },
    {
        id: 'f1-azerbaijan-2026',
        name: 'Azerbaijan Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'September 24–26, 2026',
        startDate: new Date('2026-09-24'),
        endDate: new Date('2026-09-26'),
        country: 'Azerbaijan',
        venue: 'Baku City Circuit',
        city: 'Baku',
        description: 'Dramatic street circuit through old Baku with long straights and tight castle section.',
        imageUrl: 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Street Circuit', 'Dramatic', 'Castle Section'],
        highlights: ['Dramatic street circuit', 'Old city views', 'Unpredictable racing'],
        targetAudience: ['Adventure Seekers', 'Culture Enthusiasts']
    },
    {
        id: 'f1-singapore-2026',
        name: 'Singapore Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'October 9–11, 2026',
        startDate: new Date('2026-10-09'),
        endDate: new Date('2026-10-11'),
        country: 'Singapore',
        venue: 'Marina Bay Street Circuit',
        city: 'Singapore',
        description: 'Sprint weekend under the lights in stunning Marina Bay - F1\'s original night race.',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Sprint Weekend', 'Night Race', 'Street Circuit', 'Marina Bay'],
        highlights: ['Sprint format', 'Stunning night race', 'Marina Bay backdrop', 'Asian hub'],
        targetAudience: ['Asian Markets', 'Night Race Fans', 'Luxury Travelers']
    },
    {
        id: 'f1-usa-austin-2026',
        name: 'United States Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'October 23–25, 2026',
        startDate: new Date('2026-10-23'),
        endDate: new Date('2026-10-25'),
        country: 'USA',
        venue: 'Circuit of the Americas',
        city: 'Austin',
        description: 'Purpose-built F1 circuit in Austin with massive US fanbase and entertainment.',
        imageUrl: 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['USA', 'Purpose Built', 'Entertainment Hub'],
        highlights: ['Growing US fanbase', 'Austin entertainment', 'Modern facilities'],
        targetAudience: ['US Fans', 'Entertainment Seekers', 'Festival Goers']
    },
    {
        id: 'f1-mexico-2026',
        name: 'Mexico City Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'October 30 – November 1, 2026',
        startDate: new Date('2026-10-30'),
        endDate: new Date('2026-11-01'),
        country: 'Mexico',
        venue: 'Autódromo Hermanos Rodríguez',
        city: 'Mexico City',
        description: 'High-altitude racing with incredibly passionate Mexican fans and vibrant atmosphere.',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['High Altitude', 'Passionate Fans', 'Latin America'],
        highlights: ['Passionate Mexican fans', 'High altitude challenge', 'Vibrant atmosphere'],
        targetAudience: ['Mexican Fans', 'Latin American Fans', 'Culture Enthusiasts']
    },
    {
        id: 'f1-brazil-2026',
        name: 'São Paulo Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'November 6–8, 2026',
        startDate: new Date('2026-11-06'),
        endDate: new Date('2026-11-08'),
        country: 'Brazil',
        venue: 'Autódromo José Carlos Pace (Interlagos)',
        city: 'São Paulo',
        description: 'Historic Interlagos circuit with passionate Brazilian fans and dramatic racing.',
        imageUrl: 'https://images.unsplash.com/photo-1516496636080-14fb876e029d?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Historic', 'Passionate Fans', 'Dramatic Racing'],
        highlights: ['Historic Interlagos', 'Passionate fans', 'Championship decider potential'],
        targetAudience: ['Brazilian Fans', 'Latin American Fans', 'F1 History Buffs']
    },
    {
        id: 'f1-usa-vegas-2026',
        name: 'Las Vegas Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'November 19–21, 2026',
        startDate: new Date('2026-11-19'),
        endDate: new Date('2026-11-21'),
        country: 'USA',
        venue: 'Las Vegas Street Circuit',
        city: 'Las Vegas',
        description: 'Spectacular night race on the Las Vegas Strip with ultimate entertainment and glamour.',
        imageUrl: 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Night Race', 'Street Circuit', 'Las Vegas Strip', 'Entertainment'],
        highlights: ['Las Vegas Strip racing', 'Ultimate entertainment', 'Night spectacle', 'Celebrity event'],
        targetAudience: ['High Spenders', 'Entertainment Seekers', 'US Fans']
    },
    {
        id: 'f1-qatar-2026',
        name: 'Qatar Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'November 27–29, 2026',
        startDate: new Date('2026-11-27'),
        endDate: new Date('2026-11-29'),
        country: 'Qatar',
        venue: 'Lusail International Circuit',
        city: 'Lusail',
        description: 'Night race at the modern Lusail circuit, penultimate round of the season.',
        imageUrl: 'https://images.unsplash.com/photo-1577223625816-7546f36a5f3b?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Night Race', 'Modern Circuit', 'Middle East'],
        highlights: ['Modern facilities', 'Night racing', 'Championship implications'],
        targetAudience: ['Middle East Fans', 'Championship Watchers']
    },
    {
        id: 'f1-abudhabi-2026',
        name: 'Abu Dhabi Grand Prix',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'Formula 1',
        dateRange: 'December 4–6, 2026',
        startDate: new Date('2026-12-04'),
        endDate: new Date('2026-12-06'),
        country: 'UAE',
        venue: 'Yas Marina Circuit',
        city: 'Abu Dhabi',
        description: 'Season finale under the lights at Yas Marina - championship decider with luxury hospitality.',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Season Finale', 'Night Race', 'Championship Decider', 'Luxury'],
        highlights: ['Season finale', 'Championship decider', 'Luxury hospitality', 'Yas Marina'],
        targetAudience: ['High Spenders', 'Championship Fans', 'Luxury Travelers']
    }
];

export const gtEuropeEvents: SportEvent[] = [
    {
        id: 'gt-paul-ricard-2026',
        name: 'GT World Challenge Europe - Paul Ricard',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'GT Racing',
        dateRange: 'April 11–12, 2026',
        startDate: new Date('2026-04-11'),
        endDate: new Date('2026-04-12'),
        country: 'France',
        venue: 'Circuit Paul Ricard',
        city: 'Le Castellet',
        description: 'Season opener for GT World Challenge Europe at the technical Paul Ricard circuit.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['GT Racing', 'Season Opener', 'Endurance'],
        highlights: ['Season opener', 'GT3 racing', 'French Riviera'],
        targetAudience: ['GT Racing Fans', 'Endurance Enthusiasts']
    },
    {
        id: 'gt-spa-24h-2026',
        name: '24 Hours of Spa',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'GT Racing',
        dateRange: 'June 24–28, 2026',
        startDate: new Date('2026-06-24'),
        endDate: new Date('2026-06-28'),
        country: 'Belgium',
        venue: 'Circuit de Spa-Francorchamps',
        city: 'Spa',
        description: 'The world\'s premier GT endurance race - 24 hours of non-stop action at legendary Spa.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['24 Hour Race', 'Endurance', 'Legendary Circuit', 'GT3'],
        highlights: ['Premier GT endurance race', '24 hours of racing', 'Legendary Spa circuit'],
        targetAudience: ['Endurance Racing Fans', 'GT Enthusiasts', 'European Fans']
    }
];

export const endurance24hEvents: SportEvent[] = [
    {
        id: '24h-dubai-2026',
        name: '24 Hours of Dubai',
        sport: SportCategory.MOTORSPORTS,
        subCategory: '24H Series',
        dateRange: 'January 16–18, 2026',
        startDate: new Date('2026-01-16'),
        endDate: new Date('2026-01-18'),
        country: 'UAE',
        venue: 'Dubai Autodrome',
        city: 'Dubai',
        description: 'Season-opening 24-hour endurance race in the desert under floodlights.',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['24 Hour Race', 'Desert', 'Night Racing', 'Endurance'],
        highlights: ['Desert endurance racing', 'International field', 'Dubai hospitality'],
        targetAudience: ['Endurance Fans', 'Middle East Travelers']
    }
];

export const otherMotorsportsEvents: SportEvent[] = [
    {
        id: 'lemans-24h-2026',
        name: '24 Hours of Le Mans',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'WEC',
        dateRange: 'June 13–14, 2026',
        startDate: new Date('2026-06-13'),
        endDate: new Date('2026-06-14'),
        country: 'France',
        venue: 'Circuit de la Sarthe',
        city: 'Le Mans',
        description: 'The world\'s biggest endurance pilgrimage - tens of thousands travel internationally for this legendary race.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['24 Hour Race', 'WEC', 'Legendary', 'Pilgrimage'],
        highlights: ['World\'s biggest motorsport pilgrimage', 'Tens of thousands travel internationally', 'Legendary endurance race'],
        targetAudience: ['Endurance Racing Fans', 'International Travelers', 'Racing Pilgrims']
    },
    {
        id: 'indy500-2026',
        name: 'Indianapolis 500',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'IndyCar',
        dateRange: 'May 24, 2026',
        startDate: new Date('2026-05-24'),
        endDate: new Date('2026-05-24'),
        country: 'USA',
        venue: 'Indianapolis Motor Speedway',
        city: 'Indianapolis',
        description: 'The Greatest Spectacle in Racing - world\'s largest single-day sporting crowd with 300,000+ fans.',
        imageUrl: 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['IndyCar', 'Oval Racing', 'Historic', 'Massive Crowd'],
        highlights: ['World\'s largest single-day sporting crowd (300k+)', 'Fans travel from every continent', 'The Greatest Spectacle in Racing'],
        targetAudience: ['IndyCar Fans', 'US Sports Fans', 'International Travelers']
    },
    {
        id: 'daytona500-2026',
        name: 'Daytona 500',
        sport: SportCategory.MOTORSPORTS,
        subCategory: 'NASCAR',
        dateRange: 'February 15, 2026',
        startDate: new Date('2026-02-15'),
        endDate: new Date('2026-02-15'),
        country: 'USA',
        venue: 'Daytona International Speedway',
        city: 'Daytona Beach',
        description: 'The Super Bowl of NASCAR - major global interest and massive U.S. motorsport tourism.',
        imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['NASCAR', 'Oval Racing', 'Super Bowl of NASCAR'],
        highlights: ['The Super Bowl of NASCAR', 'Major global interest', 'U.S. motorsport tourism'],
        targetAudience: ['NASCAR Fans', 'US Sports Fans', 'Motorsport Tourists']
    }
];

export const motorsportsEvents: SportEvent[] = [
    ...f1Events,
    ...gtEuropeEvents,
    ...endurance24hEvents,
    ...otherMotorsportsEvents
];
