import { SportEvent, SportCategory, TravelDemand, TicketDemand } from '@/types/events';

export const grandSlamEvents: SportEvent[] = [
    {
        id: 'tennis-australian-open-2026',
        name: 'Australian Open',
        sport: SportCategory.TENNIS,
        subCategory: 'Grand Slam',
        dateRange: 'January 19 – February 1, 2026',
        startDate: new Date('2026-01-19'),
        endDate: new Date('2026-02-01'),
        country: 'Australia',
        venue: 'Melbourne Park',
        city: 'Melbourne',
        description: 'First Grand Slam of the year with huge international attendance and festival atmosphere.',
        imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Grand Slam', 'Season Opener', 'Festival Atmosphere', 'Hard Court'],
        highlights: ['Huge international attendance', 'First Slam of year', 'Festival atmosphere', 'Australian summer'],
        targetAudience: ['Tennis Fans', 'International Travelers', 'Festival Seekers']
    },
    {
        id: 'tennis-french-open-2026',
        name: 'Roland Garros (French Open)',
        sport: SportCategory.TENNIS,
        subCategory: 'Grand Slam',
        dateRange: 'May 25 – June 7, 2026',
        startDate: new Date('2026-05-25'),
        endDate: new Date('2026-06-07'),
        country: 'France',
        venue: 'Stade Roland Garros',
        city: 'Paris',
        description: 'Historic clay court championship - the centrepiece of the clay season with major European travel.',
        imageUrl: 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Grand Slam', 'Clay Court', 'Historic', 'Paris'],
        highlights: ['Historic event', 'Clay season centrepiece', 'Major European travel', 'Parisian elegance'],
        targetAudience: ['Tennis Fans', 'Clay Court Enthusiasts', 'European Travelers']
    },
    {
        id: 'tennis-wimbledon-2026',
        name: 'Wimbledon',
        sport: SportCategory.TENNIS,
        subCategory: 'Grand Slam',
        dateRange: 'June 29 – July 12, 2026',
        startDate: new Date('2026-06-29'),
        endDate: new Date('2026-07-12'),
        country: 'Great Britain',
        venue: 'All England Lawn Tennis Club',
        city: 'London',
        description: 'The world\'s most prestigious tennis tournament with extremely high ticket demand and British tradition.',
        imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Grand Slam', 'Grass Court', 'Most Prestigious', 'British Tradition'],
        highlights: ['World\'s most prestigious tournament', 'Extremely high ticket demand', 'British tradition', 'Grass court tennis'],
        targetAudience: ['Tennis Fans', 'Tradition Seekers', 'British Culture Enthusiasts']
    },
    {
        id: 'tennis-us-open-2026',
        name: 'US Open',
        sport: SportCategory.TENNIS,
        subCategory: 'Grand Slam',
        dateRange: 'August 31 – September 13, 2026',
        startDate: new Date('2026-08-31'),
        endDate: new Date('2026-09-13'),
        country: 'USA',
        venue: 'USTA Billie Jean King National Tennis Center',
        city: 'New York',
        description: 'Biggest tennis crowd in the world with major international tourism in the heart of New York City.',
        imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Grand Slam', 'Hard Court', 'New York', 'Biggest Crowd'],
        highlights: ['Biggest tennis crowd in the world', 'Major international tourism', 'New York City energy', 'Night sessions'],
        targetAudience: ['Tennis Fans', 'US Sports Fans', 'NYC Tourists']
    }
];

export const masters1000Events: SportEvent[] = [
    {
        id: 'tennis-indian-wells-2026',
        name: 'Indian Wells Masters',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'March 12 – March 22, 2026',
        startDate: new Date('2026-03-12'),
        endDate: new Date('2026-03-22'),
        country: 'USA',
        venue: 'Indian Wells Tennis Garden',
        city: 'Indian Wells, California',
        description: 'Known as the "5th Slam" with huge global travel crowd in the California desert.',
        imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', '5th Slam', 'Desert', 'Premium Event'],
        highlights: ['Known as the "5th Slam"', 'Huge global travel crowd', 'Desert paradise', 'Premium facilities'],
        targetAudience: ['Tennis Fans', 'Luxury Travelers', 'California Tourists']
    },
    {
        id: 'tennis-miami-open-2026',
        name: 'Miami Open',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'March 25 – April 5, 2026',
        startDate: new Date('2026-03-25'),
        endDate: new Date('2026-04-05'),
        country: 'USA',
        venue: 'Hard Rock Stadium',
        city: 'Miami',
        description: 'Vacation destination with very high international turnout and Miami glamour.',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Beach City', 'Vacation Destination', 'Glamour'],
        highlights: ['Vacation destination', 'Very high international turnout', 'Miami beach vibes', 'Celebrity attendance'],
        targetAudience: ['Tennis Fans', 'Beach Lovers', 'Party Seekers']
    },
    {
        id: 'tennis-monte-carlo-2026',
        name: 'Monte-Carlo Masters',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'April 13 – April 19, 2026',
        startDate: new Date('2026-04-13'),
        endDate: new Date('2026-04-19'),
        country: 'Monaco',
        venue: 'Monte Carlo Country Club',
        city: 'Monaco',
        description: 'Luxury, prestige, and high tourism on the stunning French Riviera.',
        imageUrl: 'https://images.unsplash.com/photo-1563784462041-5f97ac9523dd?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Clay Court', 'Luxury', 'Monaco', 'Riviera'],
        highlights: ['Luxury and prestige', 'High tourism', 'French Riviera views', 'Clay court elegance'],
        targetAudience: ['High Spenders', 'Luxury Travelers', 'Clay Court Fans']
    },
    {
        id: 'tennis-madrid-open-2026',
        name: 'Madrid Open',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'April 27 – May 10, 2026',
        startDate: new Date('2026-04-27'),
        endDate: new Date('2026-05-10'),
        country: 'Spain',
        venue: 'Caja Mágica',
        city: 'Madrid',
        description: 'Massive European attendance at the high-altitude clay court event in Spain\'s capital.',
        imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Clay Court', 'High Altitude', 'Spanish Capital'],
        highlights: ['Massive European attendance', 'High altitude tennis', 'Madrid culture', 'Clay court action'],
        targetAudience: ['European Fans', 'Clay Court Enthusiasts', 'Spanish Culture Lovers']
    },
    {
        id: 'tennis-rome-masters-2026',
        name: 'Italian Open (Rome Masters)',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'May 11 – May 24, 2026',
        startDate: new Date('2026-05-11'),
        endDate: new Date('2026-05-24'),
        country: 'Italy',
        venue: 'Foro Italico',
        city: 'Rome',
        description: 'Historic clay court event with strong European travel in the heart of Rome.',
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Clay Court', 'Historic', 'Rome'],
        highlights: ['Historic event', 'Strong European travel', 'Rome tourism', 'Clay court tradition'],
        targetAudience: ['European Fans', 'History Buffs', 'Italian Culture Enthusiasts']
    },
    {
        id: 'tennis-canada-open-2026',
        name: 'Canadian Open',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'August 10 – August 16, 2026',
        startDate: new Date('2026-08-10'),
        endDate: new Date('2026-08-16'),
        country: 'Canada',
        venue: 'Rotating (Toronto/Montreal)',
        city: 'Toronto or Montreal',
        description: 'Alternates between cities with major North American attendance.',
        imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Masters 1000', 'Hard Court', 'Canada', 'Summer'],
        highlights: ['Alternates cities', 'Major North American attendance', 'Summer tennis', 'Canadian hospitality'],
        targetAudience: ['North American Fans', 'Canadian Tourists', 'Summer Travelers']
    },
    {
        id: 'tennis-cincinnati-masters-2026',
        name: 'Cincinnati Masters',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'August 17 – August 23, 2026',
        startDate: new Date('2026-08-17'),
        endDate: new Date('2026-08-23'),
        country: 'USA',
        venue: 'Lindner Family Tennis Center',
        city: 'Cincinnati, Ohio',
        description: 'Huge lead-in event to the US Open with top player participation.',
        imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Masters 1000', 'Hard Court', 'US Open Prep'],
        highlights: ['Huge lead-in to US Open', 'Top player field', 'US summer tennis'],
        targetAudience: ['US Tennis Fans', 'US Open Prep Watchers']
    },
    {
        id: 'tennis-shanghai-masters-2026',
        name: 'Shanghai Masters',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'October 12 – October 18, 2026',
        startDate: new Date('2026-10-12'),
        endDate: new Date('2026-10-18'),
        country: 'China',
        venue: 'Qizhong Forest Sports City Arena',
        city: 'Shanghai',
        description: 'Biggest tennis event in Asia with strong global travel and Chinese fanbase.',
        imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Asia', 'Hard Court', 'Modern Facilities'],
        highlights: ['Biggest event in Asia', 'Strong global travel', 'Chinese market', 'Modern venue'],
        targetAudience: ['Asian Markets', 'International Travelers', 'Tennis Fans']
    },
    {
        id: 'tennis-paris-masters-2026',
        name: 'Paris Masters',
        sport: SportCategory.TENNIS,
        subCategory: 'Masters 1000',
        dateRange: 'November 2 – November 8, 2026',
        startDate: new Date('2026-11-02'),
        endDate: new Date('2026-11-08'),
        country: 'France',
        venue: 'AccorHotels Arena',
        city: 'Paris',
        description: 'Indoor event that sells out fast - final Masters before ATP Finals.',
        imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Masters 1000', 'Indoor', 'Paris', 'Sells Out Fast'],
        highlights: ['Indoor event', 'Sells out fast', 'Paris atmosphere', 'Final Masters'],
        targetAudience: ['European Fans', 'Indoor Tennis Fans', 'Paris Tourists']
    }
];

export const atpFinalsEvents: SportEvent[] = [
    {
        id: 'tennis-atp-finals-2026',
        name: 'ATP Finals',
        sport: SportCategory.TENNIS,
        subCategory: 'Year-End Championship',
        dateRange: 'November 15 – November 22, 2026',
        startDate: new Date('2026-11-15'),
        endDate: new Date('2026-11-22'),
        country: 'Italy',
        venue: 'Pala Alpitour',
        city: 'Turin',
        description: 'Elite year-end championship with only top 8 players - very high demand and global spectators.',
        imageUrl: 'https://images.unsplash.com/photo-1541872703-74c34d726e5d?q=80&w=1200',
        travelDemand: TravelDemand.HIGH,
        ticketDemand: TicketDemand.EXTREME,
        tags: ['Year-End Championship', 'Top 8 Only', 'Elite', 'Indoor'],
        highlights: ['Only top 8 players', 'Very high demand', 'Global spectators', 'Season finale'],
        targetAudience: ['Tennis Fans', 'Elite Event Seekers', 'European Travelers']
    }
];

export const otherTennisEvents: SportEvent[] = [
    {
        id: 'tennis-laver-cup-2026',
        name: 'Laver Cup',
        sport: SportCategory.TENNIS,
        subCategory: 'Exhibition',
        dateRange: 'September 25–27, 2026',
        startDate: new Date('2026-09-25'),
        endDate: new Date('2026-09-27'),
        country: 'TBD',
        venue: 'TBD',
        city: 'TBD',
        description: 'Big-show atmosphere with team format - Europe vs World.',
        imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.HIGH,
        tags: ['Team Format', 'Exhibition', 'Big Show', 'Europe vs World'],
        highlights: ['Big-show atmosphere', 'Team format', 'Star players', 'Unique format'],
        targetAudience: ['Tennis Fans', 'Team Event Enthusiasts', 'Exhibition Seekers']
    },
    {
        id: 'tennis-queens-club-2026',
        name: 'Queen\'s Club Championships',
        sport: SportCategory.TENNIS,
        subCategory: 'ATP 500',
        dateRange: 'June 15–21, 2026',
        startDate: new Date('2026-06-15'),
        endDate: new Date('2026-06-21'),
        country: 'Great Britain',
        venue: 'Queen\'s Club',
        city: 'London',
        description: 'Beautiful grass event with intimate atmosphere - traditional Wimbledon warm-up.',
        imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?q=80&w=1200',
        travelDemand: TravelDemand.MEDIUM,
        ticketDemand: TicketDemand.MEDIUM,
        tags: ['Grass Court', 'Wimbledon Prep', 'Intimate', 'Traditional'],
        highlights: ['Beautiful grass event', 'Intimate atmosphere', 'Wimbledon warm-up', 'British tradition'],
        targetAudience: ['Grass Court Fans', 'British Tennis Enthusiasts', 'Tradition Seekers']
    }
];

export const tennisEvents: SportEvent[] = [
    ...grandSlamEvents,
    ...masters1000Events,
    ...atpFinalsEvents,
    ...otherTennisEvents
];
